### ISSUE TITLE
Not working properly after android 8

### ISSUE THREAD

**Issue by vedprakashsah1998** [fanysoft/Android_WeatherWidgetApp#1]
is:issue is:open Not working widget after app is closed and even if the app is open the weather report from openweather map api is not call

it shows error
2021-03-06 01:55:34.559 2126-2155/? E/AndroidRuntime: FATAL EXCEPTION: e.z Dispatcher
    Process: cz.vancura.weatherwidget, PID: 2126
    java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at g.g$b$a.b(:82)
        at g.l$a.c(:161)
        at e.h0.g.e$a.run(:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at g.g$b$a.b(:82) 
        at g.l$a.c(:161) 
        at e.h0.g.e$a.run(:519) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by vedprakashsah1998** [comment]
no issues just add 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
in gradle file but List shows null value
